project_name: renderizer
builds:
  -
    binary: renderizer
    goos:
      - darwin
    goarch:
      - amd64
    ldflags: '-s -w -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.commit={{.Commit}} -X main.date={{ time "20060102T150405" }}'

dist: build/dist

release:
  draft: true
