language: go
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "tip"
notificaitons:
  email:
    recipients:
      gomatic@nicerobot.org
    on_success: change
    on_failure: always
install:
  - go get -t ./pkg/... ./cmd/...
script:
  - go test -v ./pkg/... ./cmd/...
