version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/gomatic/renderizer
    steps:
      - checkout
      - run: make
